Repository datosgobar/portal-andino, pull requests merged in 2018-04, with the labels that each got.

#107 102 actualizar docs
  docs/assets/portal-andino-asig-recurso.png
  docs/assets/portal-andino-asig-tags.png
  docs/assets/portal-andino-campos-avanzados.jpg
  docs/assets/portal-andino-campos-especiales.jpg
  docs/assets/portal-andino-comoveo-org.png
  docs/assets/portal-andino-crear-dataset.png
  docs/assets/portal-andino-crear-org.png
  docs/assets/portal-andino-dat-tags.png
  docs/assets/portal-andino-form-temas.png
  docs/assets/portal-andino-header.png
  docs/assets/portal-andino-login.png
  docs/assets/portal-andino-metadatos.jpg
  docs/assets/portal-andino-sec-acerca-02.png
  docs/assets/portal-andino-sec-acerca-03.png
  docs/assets/portal-andino-sec-acerca-04.png
  docs/assets/portal-andino-sec-acerca.png
  docs/assets/portal-andino-sec-config.png
  docs/assets/portal-andino-sec-org-02.png
  docs/assets/portal-andino-sec-org.png
  docs/assets/portal-andino-sec-temas-02.png
  docs/assets/portal-andino-sec-temas-03.png
  docs/assets/portal-andino-sec-temas.png
  docs/assets/portal-andino-user.png
  docs/developers/docker.md
  docs/developers/install.md
  docs/developers/maintenance.md
  docs/developers/migration.md
  docs/developers/tests.md
  docs/developers/update.md
  docs/index.md
  docs/quickstart.md
  docs/setup/recommendations.md
  docs/setup/update.md
  docs/setup/usage.md
  docs/usage.md
  mkdocs.yml
Labels: in progress

#106 Se modifica el dockerfile para que se copie el archivo que contiene l…
  Dockerfile
Labels: in progress, portal-andino

#111 Configuracion HTTPS
  docs/admins/https.md
  docs/developers/tests.md
  docs/index.md
Labels: 1 sp, in progress

#120 Update Dockerfile
  Dockerfile
Labels: in progress

#119 Cambio nombre del archivo 'about_template.html' a 'seccion-acerca.html'.
  Dockerfile
Labels: in progress, portal-andino

#122 121 documentar config dns
  docs/developers/dns.md
  docs/developers/https.md
  docs/developers/tests.md
  docs/developers/update.md
  docs/index.md
  mkdocs.yml
Labels: in progress
